apiVersion: v1
kind: Pod
metadata:
  name: fastify-backend
  labels:
    app: fastify-backend
spec:
  containers:
    - name: fastify-backend
      image: fastify-backend:latest
      env:
        - name: PORT
          value: '3000'
        - name: ZIPKIN
          value: 'zipkin:9411'
      ports:
        - name: fetcher-port
          containerPort: 3000
      imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 0

---
apiVersion: v1
kind: Service
metadata:
  name: fastify-backend
spec:
  type: NodePort
  selector:
    app: fastify-backend
  ports:
    - name: fetcher-port
      port: 3000
      targetPort: 3000
      nodePort: 30002