apiVersion: v1
kind: Pod
metadata:
  name: fastify-backend
  labels:
    app: fastify-backend
    owner: zbio
    managed-by: roost
spec:
  containers:
    - name: fastify-backend
      image: fastify-backend:latest
      env:
        - name: STORAGE_DIR
          value: /app-store
      volumeMounts:
        - mountPath: /app-store
          name: article-storage
      resources:
        limits:
          memory: "128Mi"
          cpu: "200m"
      ports:
        - name: fetcher-port
          containerPort: 3000
      imagePullPolicy: Never
  terminationGracePeriodSeconds: 0
  volumes:
    - name: article-storage
      emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: fastify-backend
  labels:
    owner: zbio
    managed-by: roost
spec:
  selector:
    app: fastify-backend
  ports:
    - name: fetch-svc-port
      port: 3000
      targetPort: 3000