apiVersion: v1
kind: Pod
metadata:
  name: fastify-frontend
  labels:
    app: fastify-frontend
    owner: zbio
    managed-by: roost
spec:
  containers:
    - name: fastify-frontend
      image: fastify-frontend:latest
      env:
        - name: BACKEND_URL
          value: "http://fastify-backend:3000"
      # resources:
      #   limits:
      #     memory: "128Mi"
      #     cpu: "200m"
      ports:
        - name: retriever-port
          containerPort: 3000
      imagePullPolicy: Never
  terminationGracePeriodSeconds: 0

---
apiVersion: v1
kind: Service
metadata:
  name: fastify-frontend
  labels:
    owner: zbio
    managed-by: roost
spec:
  type: NodePort
  selector:
    app: fastify-frontend
  ports:
    - name: retriever-port
      port: 3001
      targetPort: 3000
      nodePort: 30001
